#!/usr/bin/env python3

# Author: Yotam Gingold <yotam@yotamgingold.com>
# License: Public Domain (CC0)
# URL: https://gist.github.com/yig/e59eaa22f5042320ecf18a87da4e44ae


from pathlib import Path

SKIP_DIRS = [".git", "index.html","index.py","script",".github"]
exclude=SKIP_DIRS

def make_index_html( path ):
    path = Path(path)
    if not path.is_dir():
        raise TypeError( f'Path is not a directory: {path}' )
    
    assert path.is_dir()
    
	## Navigate to inside current folder!
    path = path / 'fan-stuff'
    
    title = path.resolve().name

    print( "Generating index.html for", title )
    
    ## Open index.html
    with open( path / 'index.html', 'w' ) as out:
        
        ## Write the header
        out.write( title.join( HEADERS ) )
        
				## Write body!
        out.write( '''
                  <p>
                  this is where I put my fan-stuff
                  <br><br>
                  </p>
                  ''' )

        
        out.write( '''
          <table>
					''' )
        # out.write( '''
        #   <table>
				# 	<tr><th>Name</th><th>Size</th></tr>
				# 	''' )
        
        ## Write a row for each file.
        for file in sorted(list(path.iterdir())):
            ## Skip the excluded files / folders.
            if file.name in exclude : 
                    continue
            
            ## File Size function
            #size_in_bytes = file.stat().st_size
            #pretty_size = HumanBytes.format( size_in_bytes, precision = 0 )
            #out.write( f'<tr><td><a href="{file.name}">{file.name}</a></td><td>{pretty_size}</td></tr>\n'  )
            out.write( f'<tr><td><a href="{file.name}">{file.name}</a></td></tr>\n'  )
        
        ## Write the footer.
        out.write( '''
					</table>
					<br>
     
        Insert a HOME Button    vvvv  Replace the URL with your Home Page  vvvvv
	<p><strong>
					<a href="https://hotlink-archive-template.pages.dev/">Home</a>
					</strong></p>
 
					</body>
					</html>
					''' )

## https://stackoverflow.com/questions/12523586/python-format-size-application-converting-b-to-kb-mb-gb-tb/63839503#63839503
# from typing import List, Union
# class HumanBytes:
#     METRIC_LABELS: List[str] = ["B", "kB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"]
#     BINARY_LABELS: List[str] = ["B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB", "ZiB", "YiB"]
#     PRECISION_OFFSETS: List[float] = [0.5, 0.05, 0.005, 0.0005] # PREDEFINED FOR SPEED.
#     PRECISION_FORMATS: List[str] = ["{}{:.0f} {}", "{}{:.1f} {}", "{}{:.2f} {}", "{}{:.3f} {}"] # PREDEFINED FOR SPEED.

#     @staticmethod
#     def format(num: Union[int, float], metric: bool=False, precision: int=1) -> str:
#         """
#         Human-readable formatting of bytes, using binary (powers of 1024)
#         or metric (powers of 1000) representation.
#         """

#         assert isinstance(num, (int, float)), "num must be an int or float"
#         assert isinstance(metric, bool), "metric must be a bool"
#         assert isinstance(precision, int) and precision >= 0 and precision <= 3, "precision must be an int (range 0-3)"

#         unit_labels = HumanBytes.METRIC_LABELS if metric else HumanBytes.BINARY_LABELS
#         last_label = unit_labels[-1]
#         unit_step = 1000 if metric else 1024
#         unit_step_thresh = unit_step - HumanBytes.PRECISION_OFFSETS[precision]

#         is_negative = num < 0
#         if is_negative: # Faster than ternary assignment or always running abs().
#             num = abs(num)

#         for unit in unit_labels:
#             if num < unit_step_thresh:
#                 # VERY IMPORTANT:
#                 # Only accepts the CURRENT unit if we're BELOW the threshold where
#                 # float rounding behavior would place us into the NEXT unit: F.ex.
#                 # when rounding a float to 1 decimal, any number ">= 1023.95" will
#                 # be rounded to "1024.0". Obviously we don't want ugly output such
#                 # as "1024.0 KiB", since the proper term for that is "1.0 MiB".
#                 break
#             if unit != last_label:
#                 # We only shrink the number if we HAVEN'T reached the last unit.
#                 # NOTE: These looped divisions accumulate floating point rounding
#                 # errors, but each new division pushes the rounding errors further
#                 # and further down in the decimals, so it doesn't matter at all.
#                 num /= unit_step

#         return HumanBytes.PRECISION_FORMATS[precision].format("-" if is_negative else "", num, unit)

HEADERS = ['''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="Author" content="Generated by index.html.py @ https://gist.github.com/yig/e59eaa22f5042320ecf18a87da4e44ae">
<title>''', '''</title>
<!-- <link rel="stylesheet" href="https://fonts.xz.style/serve/inter.css"> -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@exampledev/new.css@1.1.2/new.min.css"> -->
<!-- <link rel="stylesheet" href="fonts/Inter/inter.css"> -->
<!-- <link rel="stylesheet" href="new.css"> -->
<!-- The following <style> is new.css from https://newcss.net or https://github.com/xz/new.css -->
<!--
MIT License

Copyright (c) 2020 Example (https://github.com/3x)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->
<style type="text/css">
:root {
	--nc-font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
	--nc-font-mono: Consolas, monaco, 'Ubuntu Mono', 'Liberation Mono', 'Courier New', Courier, monospace;

	/* Light theme */
	--nc-tx-1: #000000;
	--nc-tx-2: #1A1A1A;
	--nc-bg-1: #FFFFFF;
	--nc-bg-2: #F6F8FA;
	--nc-bg-3: #E5E7EB;
	--nc-lk-1: #0070F3;
	--nc-lk-2: #0366D6;
	--nc-lk-tx: #FFFFFF;
	--nc-ac-1: #79FFE1;
	--nc-ac-tx: #0C4047;

	/* Dark theme */
	--nc-d-tx-1: #ffffff;
	--nc-d-tx-2: #eeeeee;
	--nc-d-bg-1: #000000;
	--nc-d-bg-2: #111111;
	--nc-d-bg-3: #222222;
	--nc-d-lk-1: #3291FF;
	--nc-d-lk-2: #0070F3;
	--nc-d-lk-tx: #FFFFFF;
	--nc-d-ac-1: #7928CA;
	--nc-d-ac-tx: #FFFFFF;
}

@media (prefers-color-scheme: dark) {
	:root {
		--nc-tx-1: var(--nc-d-tx-1);
		--nc-tx-2: var(--nc-d-tx-2);
		--nc-bg-1: var(--nc-d-bg-1);
		--nc-bg-2: var(--nc-d-bg-2);
		--nc-bg-3: var(--nc-d-bg-3);
		--nc-lk-1: var(--nc-d-lk-1);
		--nc-lk-2: var(--nc-d-lk-2);
		--nc-lk-tx: var(--nc--dlk-tx);
		--nc-ac-1: var(--nc-d-ac-1);
		--nc-ac-tx: var(--nc--dac-tx);
	}
}

* {
	/* Reset margins and padding */
	margin: 0;
	padding: 0;
}

address,
area,
article,
aside,
audio,
blockquote,
datalist,
details,
dl,
fieldset,
figure,
form,
input,
iframe,
img,
meter,
nav,
ol,
optgroup,
option,
output,
p,
pre,
progress,
ruby,
section,
table,
textarea,
ul,
video {
	/* Margins for most elements */
	margin-bottom: 1rem;
}

html,input,select,button {
	/* Set body font family and some finicky elements */
	font-family: var(--nc-font-sans);
}

body {
	/* Center body in page */
	margin: 0 auto;
	max-width: 750px;
	padding: 2rem;
	border-radius: 6px;
	overflow-x: hidden;
	word-break: break-word;
	overflow-wrap: break-word;
	background: var(--nc-bg-1);

	/* Main body text */
	color: var(--nc-tx-2);
	font-size: 1.03rem;
	line-height: 1.5;
}

::selection {
	/* Set background color for selected text */
	background: var(--nc-ac-1);
	color: var(--nc-ac-tx);
}

h1,h2,h3,h4,h5,h6 {
	line-height: 1;
	color: var(--nc-tx-1);
	padding-top: .875rem;
}

h1,
h2,
h3 {
	color: var(--nc-tx-1);
	padding-bottom: 2px;
	margin-bottom: 8px;
	border-bottom: 1px solid var(--nc-bg-2);
}

h4,
h5,
h6 {
	margin-bottom: .3rem;
}

h1 {
	font-size: 2.25rem;
}

h2 {
	font-size: 1.85rem;
}

h3 {
	font-size: 1.55rem;
}

h4 {
	font-size: 1.25rem;
}

h5 {
	font-size: 1rem;
}

h6 {
	font-size: .875rem;
}

a {
	color: var(--nc-lk-1);
}

a:hover {
	color: var(--nc-lk-2);
}

abbr:hover {
	/* Set the '?' cursor while hovering an abbreviation */
	cursor: help;
}

blockquote {
	padding: 1.5rem;
	background: var(--nc-bg-2);
	border-left: 5px solid var(--nc-bg-3);
}

abbr {
	cursor: help;
}

blockquote *:last-child {
	padding-bottom: 0;
	margin-bottom: 0;
}

header {
	background: var(--nc-bg-2);
	border-bottom: 1px solid var(--nc-bg-3);
	padding: 2rem 1.5rem;
	
	/* This sets the right and left margins to cancel out the body's margins. It's width is still the same, but the background stretches across the page's width. */

	margin: -2rem calc(0px - (50vw - 50%)) 2rem;

	/* Shorthand for:

	margin-top: -2rem;
	margin-bottom: 2rem;

	margin-left: calc(0px - (50vw - 50%));
	margin-right: calc(0px - (50vw - 50%)); */
	
	padding-left: calc(50vw - 50%);
	padding-right: calc(50vw - 50%);
}

header h1,
header h2,
header h3 {
	padding-bottom: 0;
	border-bottom: 0;
}

header > *:first-child {
	margin-top: 0;
	padding-top: 0;
}

header > *:last-child {
	margin-bottom: 0;
}



hr {
	/* Reset the border of the <hr> separator, then set a better line */
	border: 0;
	border-bottom: 1px solid var(--nc-bg-3);
	margin: 1rem auto;
}

fieldset {
	margin-top: 1rem;
	padding: 2rem;
	border: 1px solid var(--nc-bg-3);
	border-radius: 4px;
}

legend {
	padding: auto .5rem;
}

table {
	/* border-collapse sets the table's elements to share borders, rather than floating as separate "boxes". */
	border-collapse: collapse;
	width: 100%;
}

td,
th {
	border: 1px solid var(--nc-bg-3);
	text-align: left;
	padding: .5rem;
}

th {
	background: var(--nc-bg-2);
}

tr:nth-child(even) {
	/* Set every other cell slightly darker. Improves readability. */
	background: var(--nc-bg-2);
}

table caption {
	font-weight: bold;
	margin-bottom: .5rem;
}

textarea {
	/* Don't let the <textarea> extend off the screen naturally or when dragged by the user */
	max-width: 100%;
}

ol,
ul {
	/* Replace the browser default padding */
	padding-left: 2rem;
}

li {
	margin-top: .4rem;
}

ul ul,
ol ul,
ul ol,
ol ol {
	margin-bottom: 0;
}

mark {
	padding: 3px 6px;
	background: var(--nc-ac-1);
	color: var(--nc-ac-tx);
}

textarea,
select,
input {
	padding: 6px 12px;
	margin-bottom: .5rem;
	background: var(--nc-bg-2);
	color: var(--nc-tx-2);
	border: 1px solid var(--nc-bg-3);
	border-radius: 4px;
	box-shadow: none;
	box-sizing: border-box;
}

img {
	max-width: 100%;
}
</style>
</head>
<body>
<header><h1 class="title">''', '''</h1></header>
''']

# if __name__ == '__main__': make_index_html('.')
make_index_html('.')
